import { createFileRoute } from "@tanstack/react-router";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — CompareX by Tanveershows" },
      { name: "description", content: "The terms that govern your use of CompareX, a product by Tanveershows." },
      { name: "robots", content: "index,follow" },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <SiteHeader />
      <section className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-16">
        <h1 className="text-4xl font-extrabold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: July 15, 2026 · Maintained by Tanveershows for CompareX.
        </p>

        <div className="mt-8 space-y-6 text-sm text-foreground/90 leading-relaxed">
          <div>
            <h2 className="text-lg font-semibold">1. Acceptance</h2>
            <p className="mt-2 text-muted-foreground">
              By accessing or using CompareX (the "Service"), operated by Tanveershows, you
              agree to be bound by these Terms. If you do not agree, do not use the Service.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold">2. Use of the service</h2>
            <p className="mt-2 text-muted-foreground">
              You agree to use CompareX for lawful purposes only. You may not misuse, disrupt,
              reverse engineer, or attempt to gain unauthorized access to the Service.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold">3. AI-generated content</h2>
            <p className="mt-2 text-muted-foreground">
              Comparisons, winners, and recommendations are generated by AI and provided for
              informational purposes only. Specs and prices may be inaccurate, outdated, or
              estimated. Always verify with the manufacturer before making a purchase.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold">4. User reviews</h2>
            <p className="mt-2 text-muted-foreground">
              You are responsible for content you post. Do not submit unlawful, defamatory, or
              infringing content. We may remove reviews that violate these Terms.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold">5. Intellectual property</h2>
            <p className="mt-2 text-muted-foreground">
              CompareX, its design, and its software are owned by Tanveershows. Product names
              and trademarks referenced belong to their respective owners.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold">6. Disclaimer & liability</h2>
            <p className="mt-2 text-muted-foreground">
              The Service is provided "as is" without warranties of any kind. To the fullest
              extent permitted by law, Tanveershows is not liable for any indirect or
              consequential damages arising from your use of the Service.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold">7. Changes</h2>
            <p className="mt-2 text-muted-foreground">
              We may update these Terms from time to time. Continued use of the Service after
              changes means you accept the revised Terms.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold">8. Contact</h2>
            <p className="mt-2 text-muted-foreground">
              For questions about these Terms, contact Tanveershows at{" "}
              <span className="text-foreground">support@tanveershows.com</span>.
            </p>
          </div>
        </div>
      </section>
      <SiteFooter />
    </div>
  );
}
